beta/beta/app/urls.py
"""
Definition of urls for polls viewing and voting.
"""

from django.views.generic import TemplateView
from django.conf.urls import patterns, url, include
from app.models import Poll
from app.views import PollListView, PollDetailView, PollResultsView
from .views import SignUpView


from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',
        PollListView.as_view(
            queryset=Poll.objects.order_by('-pub_date')[:5],
            context_object_name='latest_poll_list',
            template_name='app/index.html',),
        name='home'),
    url(r'^(?P<pk>\d+)/$',
        PollDetailView.as_view(
            template_name='app/details.html'),
        name='detail'),
    url(r'^(?P<pk>\d+)/results/$',
        PollResultsView.as_view(
            template_name='app/results.html'),
        name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', 'app.views.vote', name='vote'),
    #url(r'^home$', 'home', name='app_home'),
    url(r'^signup$', 
        SignUpView.as_view(
            template_name= 'app/signup.html'), 
        name='signup'),
    url(r'^fullcalendar/', TemplateView.as_view(template_name="app/fullcalendar.html"), name='fullcalendar'),
    url(r'^schedule/', include('schedule.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

beta/beta/beta/urls.py
"""
Definition of urls for beta.
"""

from django.views.generic import TemplateView
from datetime import datetime
from django.conf.urls import patterns, include, url
from django.contrib import admin
from app.forms import BootstrapAuthenticationForm


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('app.urls', namespace="app")),
    url(r'^contact$', 'app.views.contact', name='contact'),
    url(r'^about', 'app.views.about', name='about'),
    url(r'^seed', 'app.views.seed', name='seed'),
    url(r'^', include('schedule.urls')),
    url(r'^login/$',
        'django.contrib.auth.views.login',
        {
            'template_name': 'app/login.html',
            'authentication_form': BootstrapAuthenticationForm,
            'extra_context':
            {
                'title':'Log in',
                'year':datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        'django.contrib.auth.views.logout',
        {
            'next_page': '/',
        },
        name='logout'),
    url(r'^fullcalendar/', TemplateView.as_view(template_name="app/fullcalendar.html"), name='fullcalendar'),
    url(r'^schedule/', include('schedule.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

beta/beta/app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{title}}.</h2>

<p>This is a sample polls application that demonstrates the use of Django web framework.</p>
<h3>Problem</h3>
    <p>When companies come to campus, they often hold talks or events and the students usually need to login, write names, or sign-in so they can have the students information
There is also a difficulty to measure the impact of events </p>

<h3>Proposed Solution</h3>
<p>Implement a responsive web application for logging in at the beginning of events
Have a mobile application on devices and students choose to login and logout at the end of events
Events will then be posted on the web or mobile application and students will take an impact survey after each event
Once the student completes the survey they gain points which they can accumulate throughout the semester
The points can be used in a raffle draw at the end of the semester to provide the winner with meaningful prizes/swag
</p>
<h3>Effect</h3>

<p>Attendance at events will increase 
Student's reactions/feedback will be tracked throughout the semester
Students will gain new information attending these events </p>
{% endblock %}

beta/beta/app/templates/app/base.html
{% extends "layout.html" %}
{% load staticfiles i18n %}
{% block extra_head %}
{{ block.super }}
{% endblock %}

{% block rtab_id %}id="schedule_tab"{% endblock %}

{% block subnav %}
<ul>
    {% if user.is_authenticated %}
        <li><a href="">{% trans "Create a Calendar" %}</a></li>
        <li><a href="">{% trans "Your Calendars" %}</a></li>
    {% endif %}

        <li><a href="">{% trans "All Calendars" %}</a></li>
    </ul>
{% endblock %}

beta/beta/app/templates/app/calendar.html
{% extends "site_base.html" %}


{% load i18n staticfiles %}

{% block head_title %}{% trans "Fullcalendar" %}{% endblock %}

{% block tab_id %}id="home_tab"{% endblock %}

{% block extra_head %}
<link rel='stylesheet' type='text/css' href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.css" />
<script type='text/javascript' src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.min.js"></script>
{% endblock %}

{% block body %}
<div id="calendar"></div>
<script type='text/javascript'>
$(document).ready(function() {
    // page is now ready, initialize the calendar...
    $('#calendar').fullCalendar({
        // put your options and callbacks here
      events: '/schedule/api/occurrences?calendar_slug=example'
    })
});
</script>

{% endblock %}

beta/beta/app/templates/app/calendar_month.html
{#{% extends "layout.html" %}
{% load i18n calendarium_tags %}

{% block main %}
<h1>Diary Override {{ date|date:"F Y" }}</h1>
{% include "calendarium/partials/category_list.html" %}
<form action="." method="post">
    {% csrf_token %}
    <input class="btn btn-default" type="submit" name="previous" value="{% trans "Previous" %}" />
    <input class="btn btn-default" type="submit" name="next" value="{% trans "Next" %}" />
    <input class="btn btn-default" type="submit" name="today" value="{% trans "Today" %}" />
    {% if request.user.is_staff %}
        <a href="{% url "calendar_event_create" %}">{% trans "Create new event" %}</a>
    {% endif %}
</form>
<table class="table" id="calendar-month">a
    <tr>
        <th></th>
        {% for weekday in weekdays %}
            <th>{{ weekday }}</th>
        {% endfor %}
    </tr>
    {% for week in month %}
        {% if week %}
            <tr>
                <td class="calendarium-week-link"><a href="{{ date|get_week_URL:week.0.0 }}">{% trans "View" %}</a></td>
                {% for day, occurrences, current in week %}
                    <td class="{% if day == 0 %}calendarium-empty{% elif current %}calendarium-current{% else %}calendarium-day{% endif %}">
                        <div class="calendarium-relative">
                            {% if day != 0 %}
                                <span class="calendarium-date">{{ day }}</span>
                                {% for occurrence in occurrences %}
                                    <p class="alert" style="background-color: #{{ occurrence.event.category.color }}">
                                        <a title="{{ occurrence }}" 
href="{% url 'calendar_occurrence_detail' pk=occurrence.event.pk year=occurrence.start.year month=occurrence.start.month day=occurrence.start.day %}"
                                        >
                                        {{ occurrence.event.title }}
                                        </a>
                                    </p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </td>
                {% endfor %}
            </tr>
        {% endif %}
    {% endfor %}
</table>
{% render_upcoming_events 5 current_category %}
{% endblock %}#}

beta/beta/app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{title}}.</h2>

<h3>Support</h3>
<address>
    <strong>Oreo</strong> <a href="https://github.com/tems4real" target="_blank">github.com</a><br />
</address>

<h3>Links</h3>
<address>
    <strong>Django:</strong> <a href="https://www.djangoproject.com/" target="_blank">https://www.djangoproject.com/</a><br />
    <strong>Microsoft Azure:</strong> <a href="http://azure.microsoft.com/" target="_blank">http://azure.microsoft.com/</a><br />
     <strong>Professor Keiller:</strong> <a href="http://www.cs.ceacs.howard.edu/user/23" target="_blank">http://www.cs.ceacs.howard.edu/user/23</a><br />

</address>

{% endblock %}

beta/beta/app/templates/app/details.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{poll.text}}</h2>
<br />

{% if error_message %}
<p class="text-danger">{{error_message}}</p>
{% endif %}

<form action="{% url 'app:vote' poll.id %}" method="post">
{% csrf_token %}
{% for choice in poll.choice_set.all %}
    <div class="radio">
        <label>
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
            {{ choice.text }}
        </label>
    </div>
{% endfor %}
    <br />
    <button class="btn btn-primary" type="submit">Vote</button>
</form>

{% endblock %}

beta/beta/app/templates/app/fullcalendar.html
{% extends 'site_base.html' %}
{% load i18n staticfiles scheduletags %}

{% block head_title %}{% trans 'Fullcalendar' %}{% endblock %}
{% block tab_id %}id='home_tab'{% endblock %}
{% block extra_head %}

<link rel='stylesheet' type='text/css' href='//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.3.1/fullcalendar.min.css' />
<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.js'></script>
<script type='text/javascript' src='http://tarruda.github.com/bootstrap-datetimepicker/assets/js/bootstrap-datetimepicker.min.js'></script>
<script type='text/javascript' src='//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.3.1/fullcalendar.js'></script>
<script type='text/javascript'>
$(document).ready(function() {
    
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    function sameOrigin(url) {
                // test that a given url is a same-origin URL
                // url could be relative or scheme relative or absolute
                var host = document.location.host; // host + port
                var protocol = document.location.protocol;
                var sr_origin = '//' + host;
                var origin = protocol + sr_origin;
                // Allow absolute or scheme relative URLs to same origin
                return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
                    (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
                    // or any other URL that isn't scheme relative or absolute i.e relative.
                    !(/^(\/\/|http:|https:).*/.test(url));
            }

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                // Only send the token to relative URLs i.e. locally.
                xhr.setRequestHeader('X-CSRFToken', getCookie('csrftoken'));
            }
        }
    });

    $.ajaxPrefilter(function(options, originalOptions, jqXHR){
        var request_method = options['type'].toLowerCase();
        if ((request_method === 'post' || request_method === 'delete') && sameOrigin(options.url)) {
            jqXHR.setRequestHeader('X-CSRFToken', getCookie('csrftoken'));
        }
    });

    var date = new Date();
    var d = date.getDate();
    var m = date.getMonth();
    var y = date.getFullYear();

    $('#calendar').fullCalendar({
        header: {
            left: 'prev,next today',
            center: 'title',
            right: 'month,agendaWeek,agendaDay'
        },
        editable: true,
        eventLimit: true, // allow 'more' link when too many events
        selectable: true, //Allows a user to highlight multiple days or timeslots by clicking and dragging.
        selectHelper: true,
        events: '/schedule/api/occurrences?calendar_slug={{calendar_slug}}',
        loading: function(bool) {
            if (bool) {
                $('#loading').show();
            }else{
                $('#loading').hide();
            }
        },
        eventRender: function(event, element) {
            var s = element[0].className;
            if(s.indexOf("fc-day-grid-event") < 0){
                title = element.children().find( '.fc-time' );
                var edit_url = "{% url 'edit_event' calendar_slug 12345 %}".replace(/12345/, event.event_id);
                var edit_button = "<a href='"+ edit_url + 
                    "'> <button type='button' class='btn btn-primary btn-sm pull-right'><span class='glyphicon glyphicon-pencil'></span></button></a>"
                var delete_url = "{% url 'delete_event' 12345 %}".replace(/12345/, event.event_id);
                var delete_button = "<a href='"+ delete_url + 
                    "'> <button type='button' class='btn btn-primary btn-sm pull-right'><span class='glyphicon glyphicon-trash'></span></button></a>"
                title.prepend(edit_button + delete_button + '<br>');
            }
        },
        dayClick: function(date, allDay, jsEvent, view) {
                    if (allDay) {       
                        $('#calendar').fullCalendar('changeView', 'agendaWeek');
                        $("#calendar").fullCalendar('gotoDate', date);
                    }
                },
        eventClick: function(event, jsEvent, view) {
            
        },
        eventDrop: function(event,delta,revertFunc) {
            $.ajax({
                    type: 'POST',
                    url: "{% url 'api_move_or_resize' %}",
                    dataType: 'json',
                    data : {
                        'id': event.id,
                        'event_id' : event.event_id,
                        'existed' : event.existed,
                        'delta' : delta.asMinutes(),
                    },
                    success : function(result) {
                        if (result.success) $('#feedback input').attr('value', ''); 
                        $('#calendar').fullCalendar('refetchEvents');
                        },
                    error : function(req, status, error) {
                        console.log(error);
                    }
                });
            return false;
        },
        eventResize: function(event,delta,revertFunc) {
            $.ajax({
                    type: 'POST',
                    url: "{% url 'api_move_or_resize' %}",
                    dataType: 'json',
                    data : {
                        'id': event.id,
                        'event_id' : event.event_id,
                        'existed' : event.existed,
                        'delta' : delta.asMinutes(),
                        'resize' : true,
                    },
                    success : function(result) {
                        if (result.success) $('#feedback input').attr('value', ''); 
                        $('#calendar').fullCalendar('refetchEvents');
                        },
                    error : function(req, status, error) {
                        console.log(error);
                    }
                });
            return false;
        },
        select: function( start, end, jsEvent, view  ) {
            if(jsEvent.toElement.className == 'fc-bg'){
                $.ajax({
                        type: 'POST',
                        url: "{% url 'api_select_create' %}",
                        dataType: 'json',
                        data : {
                            'start': start.toISOString(),
                            'end' : end.toISOString(),
                            'calendar_slug' : '{{calendar_slug}}',
                        },
                        success : function(result) {
                            console.log(result);
                            if (result.success) $('#feedback input').attr('value', ''); 
                            $('#calendar').fullCalendar('refetchEvents');
                            },
                        error : function(req, status, error) {
                            console.log(error);
                        }
                    });
                $('#calendar').fullCalendar('unselect');
                return false;
            }
        }
    });
});
</script>
{% endblock %}

{% block body %}
<div id='calendar'></div>
{% endblock %}

beta/beta/app/templates/app/homepage.html
{% extends "app/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block tab_id %}id="home_tab"{% endblock %}

{% block body %}
<div class="jumbotron">
      <div class="container">
        <h1>django-scheduler</h1>
        <p>This project is a scheduling app. At its core are events that constitute a start and end date implemented via two DateTimeFields together with a some meta datax such as title, description, etc.</p>
        <p><a data-toggle="modal" href="#myModal" class="btn btn-primary btn-lg" role="button">Learn more »</a></p>
      </div>
    </div>


<!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Learn More!</h4>
        </div>
        <div class="modal-body">
          <p>To make it more user friendly there is the idea of EventRelation which links generic objects and an Event object.  The idea is that you will keep more information about the event in these relations such as who is authorized to view them. It could be the case that User is linked to Event to represent who is authorized to view the event, and also User is linked to event to represent who is attending the event.</p>
          <p>The EventRelation has another field called distinction.  So in the previous example we could add an EventRelation which links a User to an Event with the distinction "viewer" and another EventRelation which links a User to an Event with the distinction "attendee."</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->


<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h2>Want to see it in action?</h2>
      <p>The sample project come with two management commands that enable you to load some data:</p>
      <p><code>./manage.py load_sample_data</code></p>
      <p><code>./manage.py load_example_data</code></p>
      <p><a href="{% url "schedule" %}">{% trans "The list of available Calendars." %}</a></p>
      <p><a href="{% url "fullcalendar" %}">{% trans "Full Calendar Example" %}</a></p>
    </div>
    <div class="col-md-4">
      <h2>Contributors</h2>
      <ul>
          <li>Tony Hauber</li>
          <li>Alex Gaynor</li>
          <li>Bartek Górny</li>
          <li>Rock Howard</li>
          <li>Alik Kurdyukov</li>
          <li>Jannis Leidel</li>
          <li>Yann Malet</li>
          <li>James Pic</li>
          <li>Skylar Saveland</li>
          <li>ptoal</li>
          <li>Wes Winham</li>
          <li>Shannon Collins</li>
          <li>Leonardo Lazzaro</li>
      </ul>

    </div>
  </div>
</div>


{% endblock %}

beta/beta/app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

<h2>Howard's Computer Science</h2>
<h3>Events happening today! </h3>
<br/>
{% if latest_poll_list %}
<table class="table table-hover">
    <tbody>
        {% for poll in latest_poll_list %}
        <tr>
            <td>
                <a href="{% url 'app:detail' poll.id %}">{{poll.text}}</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>No events today.</p>
<br />
<p>You can add a set of sample polls.</p>
<form action="/seed" method="post">
    {% csrf_token %}
    <button class="btn btn-primary" type="submit">Create Sample Polls</button>
</form>
<br />
<p>You can design new polls using the Django administration interface.</p>
<p><a href="/admin" class="btn btn-primary btn-large">Django Administration &raquo;</a></p>
{% endif %}

{% endblock %}

beta/beta/app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Impact Measurement</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Impact Measurement</a>
                <a href= "{% url 'schedule' %}" class="navbar-brand">Calendar</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'about' %}">About</a></li>
                    <li><a href="{% url 'contact' %}">Contact</a></li>
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - Impact Measurement</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>

</html>


beta/beta/app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Use a local account to log in.</h4>
                <h5>To create an account <a href="/signup">Signup</a></h5>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">User name</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Password</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

beta/beta/app/templates/app/loginpartial.html
<ul class="nav navbar-nav navbar-right">
    <li><a href="/admin">Administration</a></li>
</ul>

{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Hello {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>

</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Log in</a></li>
</ul>

{% endif %}

beta/beta/app/templates/app/results.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ poll.text }}</h2>
<br />

{% for choice in poll.choice_set.all %}
<div class="row">
    <div class="col-sm-5">{{choice.text}}</div>
    <div class="col-sm-5">
        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="{{choice.votes}}" aria-valuemin="0" aria-valuemax="{{poll.total_votes}}" style="width: {{choice.votes_percentage}}%;">
                {{choice.votes}}
            </div>
        </div>
    </div>
</div>
{% endfor %}

<br />
<a class="btn btn-primary" href="{% url 'app:detail' poll.id %}">Vote again?</a>

{% endblock %}

beta/beta/app/templates/app/signup.html
{% extends "app/layout.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}


{% block title %}
New student signup
{% endblock title %}

{% block content %}
    <div class="well col-sm-6">
        <fieldset>
            <legend>
                Create an account
                </legend>
            <div class=" panel-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <p><input type="submit" value="Go!" /></p>
                    </form>
                </div>
            </fieldset>
        </div>
{% endblock  %}